apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-yexxslvg
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-yexxslvg:cea989a5a7e4f22691ef24c486c250f1d20d0961@sha256:873c2a1712cd431ed133c28d003576735c92c845e3c4977bfb5ca55b2d101cb6
          name: container-image
