apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-yexxslvg
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-yexxslvg:1c8eb56ab8101740f82de40ca79b3bc7cff937bb@sha256:68676156318d6c712f7c6b7aceede2a6930bcc82d3d9f329a6a01e2d314224b0
          name: container-image
